# Japanese translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: martin.pitt@ubuntu.com\n"
"POT-Creation-Date: 2009-06-14 23:21+0200\n"
"PO-Revision-Date: 2009-04-05 06:33+0000\n"
"Last-Translator: Nazo <lovesyao@gmail.com>\n"
"Language-Team: Japanese <ja@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2009-04-20 13:20+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#: ../gtk/apport-gtk.py:66 ../gtk/apport-gtk.py:70
#, python-format
msgid "Sorry, %s closed unexpectedly"
msgstr "残念ながら、 %s が不意に終了しました"

#: ../gtk/apport-gtk.py:68 ../apport/ui.py:153
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "残念ながら、プログラム \"%s\" が不意に終了しました"

#: ../gtk/apport-gtk.py:110 ../cli/apport-cli.py:181
msgid "Your system encountered a serious kernel problem."
msgstr "あなたのシステムは深刻なカーネルの問題に遭遇しました。"

#: ../gtk/apport-gtk.py:114 ../cli/apport-cli.py:185
msgid "You can help the developers to fix the problem by reporting it."
msgstr ""
"この問題を報告することで、問題の解決のために開発者を助けることができます。"

#: ../gtk/apport-gtk.py:145 ../cli/apport-cli.py:220
msgid "(binary data)"
msgstr "(バイナリデータ)"

#: ../gtk/apport-gtk.ui.h:1
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>不具合の情報を集めています</b></big>"

#: ../gtk/apport-gtk.ui.h:2
msgid ""
"<big><b>Send problem report to the developers?</b></big>\n"
"\n"
"After the problem report has been sent, please fill out the form in the "
"automatically opened web browser."
msgstr ""
"<big><b>開発者に不具合のレポートを送信しますか?</b></big>\n"
"\n"
"不具合のレポートが送信された後で、ウェブブラウザが自動的に開かれますので"
"フォームに入力してください。"

#: ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>不具合の情報をアップロードしています</b></big>"

#: ../gtk/apport-gtk.ui.h:7
#, no-c-format
msgid ""
"<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
"install or upgrade.</span>"
msgstr ""
"<span weight=\"bold\" size=\"larger\">申し訳ありません、パッケージ \"%s\" の"
"インストール(アップグレード)は失敗しました。</span>"

#: ../gtk/apport-gtk.ui.h:8
msgid "Application problem"
msgstr "アプリケーションの不具合"

#: ../gtk/apport-gtk.ui.h:10
#, no-c-format
msgid "Complete report (recommended; %s)"
msgstr "完全なレポート (推奨; %s)"

#: ../gtk/apport-gtk.ui.h:11
msgid "Content of the report"
msgstr "レポートの内容"

#: ../gtk/apport-gtk.ui.h:12
msgid ""
"If you were not doing anything confidential (entering passwords or other "
"private information), you can help to improve the application by reporting "
"the problem."
msgstr ""
"秘密にしておくべき作業(パスワードや個人情報の入力など)を行っていたのでなけれ"
"ば、不具合を報告してアプリケーションの改善に協力することができます。"

#: ../gtk/apport-gtk.ui.h:13
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"あなたの報告する不具合を、開発者が修正するのに役立つように情報を収集します。"

#: ../gtk/apport-gtk.ui.h:14
msgid "Kernel problem"
msgstr "カーネルの不具合"

#: ../gtk/apport-gtk.ui.h:15
msgid "Package problem"
msgstr "パッケージの不具合"

#: ../gtk/apport-gtk.ui.h:17
#, no-c-format
msgid "Reduced report (slow Internet connection; %s)"
msgstr "簡易レポート (低速回線向け; %s)"

#: ../gtk/apport-gtk.ui.h:18
msgid "Restart _Program"
msgstr "プログラムを再起動(_P)"

#: ../gtk/apport-gtk.ui.h:19
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"収集された情報はバグトラッキングシステムに送信されます。しばらくお待ちくださ"
"い。"

#: ../gtk/apport-gtk.ui.h:20
msgid ""
"This will remove some large items from the report. These are very useful for "
"developers to debug the problem, but might be too big for you to upload if "
"you have a slow internet connection."
msgstr ""
"これはいくつかの大きな項目をレポートから削除します。開発者がこの不具合をデ"
"バッグするのに大変役立ちますが、インターネットの接続スピードが遅い場合、アッ"
"プロードには大きすぎるかもしれません。"

#: ../gtk/apport-gtk.ui.h:21 ../cli/apport-cli.py:294
msgid "Uploading problem information"
msgstr "不具合の情報をアップロードしています"

#: ../gtk/apport-gtk.ui.h:22 ../cli/apport-cli.py:169
msgid ""
"You can help the developers to fix the package by reporting the problem."
msgstr "不具合を報告することで、開発者がプログラムを修正するのに役立ちます。"

#: ../gtk/apport-gtk.ui.h:23
msgid "_Ignore future crashes of this program version"
msgstr "今後このバージョンのプログラムがクラッシュしても無視する(_I)"

#: ../gtk/apport-gtk.ui.h:24
msgid "_Report Problem..."
msgstr "不具合を報告(_R)..."

#: ../gtk/apport-gtk.ui.h:25
msgid "_Send Report"
msgstr "レポートを送信(_S)"

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
msgid "Report a malfunction to the developers"
msgstr "開発者に異常動作を報告してください"

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
msgid "Report a problem..."
msgstr "不具合を報告する..."

#: ../cli/apport-cli.py:76
msgid "Press any key to continue..."
msgstr "続けるには何かキーを押してください..."

#: ../cli/apport-cli.py:83
msgid "What would you like to do? Your options are:"
msgstr "対処方法を選択してください:"

#: ../cli/apport-cli.py:87
#, python-format
msgid "Please choose (%s):"
msgstr "選択してください(%s):"

#. translators: first %s: application name, second %s: date, third %s: time
#: ../cli/apport-cli.py:144
#, python-format
msgid "%s closed unexpectedly on %s at %s."
msgstr "%s は %s の %s で不意に終了しました"

#: ../cli/apport-cli.py:148
msgid ""
"If you were not doing anything confidential (entering passwords or other\n"
"private information), you can help to improve the application by reporting\n"
"the problem."
msgstr ""
"秘密にしておくべき作業(パスワードや個人情報の入力など)を行っていたので\n"
"なければ、不具合を報告してアプリケーションの改善に協力することができます。"

#: ../cli/apport-cli.py:151 ../cli/apport-cli.py:170 ../cli/apport-cli.py:188
msgid "&Report Problem..."
msgstr "不具合を報告(&R)..."

#: ../cli/apport-cli.py:152
msgid "Cancel and &ignore future crashes of this program version"
msgstr "中止し、このプログラムバージョンでは今後クラッシュしても無視する(&I)"

#: ../cli/apport-cli.py:153 ../cli/apport-cli.py:171 ../cli/apport-cli.py:189
#: ../cli/apport-cli.py:236 ../cli/apport-cli.py:314 ../cli/apport-cli.py:346
#: ../cli/apport-cli.py:367
msgid "&Cancel"
msgstr "キャンセル（&C）"

#: ../cli/apport-cli.py:168
#, python-format
msgid "The package \"%s\" failed to install or upgrade."
msgstr "パッケージ \"%s\"のインストールまたはアップグレードに失敗しました。"

#: ../cli/apport-cli.py:200
msgid "Send problem report to the developers?"
msgstr "不具合のレポートを開発者に送信しますか?"

#: ../cli/apport-cli.py:201
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"不具合のレポートが送信された後で、フォームに入力してください（入力用ページを"
"ウェブブラウザで自動的に開きます）。"

#: ../cli/apport-cli.py:224
#, python-format
msgid "&Send complete report (recommended; %s)"
msgstr "完全なレポートの送信(&S) (推奨; %s)"

#: ../cli/apport-cli.py:226
#, python-format
msgid "Send &reduced report (slow Internet connection; %s)"
msgstr "簡易レポートの送信(&R) (低速回線向け; %s)"

#: ../cli/apport-cli.py:229
#, python-format
msgid "&Send report (%s)"
msgstr "レポートの送信(&S) (%s)"

#: ../cli/apport-cli.py:233
msgid "&View report"
msgstr "レポートの表示(&V)"

#: ../cli/apport-cli.py:234
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"後で送信もしくは他の場所にコピーするためにレポートファイルを保持する(&K)"

#: ../cli/apport-cli.py:263
msgid "Problem report file:"
msgstr "不具合報告ファイル:"

#: ../cli/apport-cli.py:271 ../cli/apport-cli.py:276
msgid "&Confirm"
msgstr "確認(&C)"

#: ../cli/apport-cli.py:275
#, python-format
msgid "Error: %s"
msgstr "エラー: %s"

#: ../cli/apport-cli.py:281
msgid "Collecting problem information"
msgstr "不具合の情報を集めています"

#: ../cli/apport-cli.py:282
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"収集された情報はアプリケーションを改善するために開発者へ送られます。\n"
"しばらくお待ちください。"

#: ../cli/apport-cli.py:295
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"収集された情報はバグトラッキングシステムに送信されます。\n"
"しばらくお待ちください。"

#: ../cli/apport-cli.py:345
msgid "&Done"
msgstr ""

#: ../cli/apport-cli.py:351
msgid "none"
msgstr ""

#: ../cli/apport-cli.py:352
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../cli/apport-cli.py:368
msgid "Choices:"
msgstr ""

#: ../cli/apport-cli.py:382
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../cli/apport-cli.py:387
#, fuzzy
msgid "File does not exist."
msgstr "パッケージ %s は存在しません"

#: ../cli/apport-cli.py:389
msgid "This is a directory."
msgstr ""

#: ../cli/apport-cli.py:396
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"未解決のクラッシュレポートはありません。詳しくは --help を試してみてくださ"
"い。"

#. TRANS: %s is the name of the operating system
#: ../apport/ui.py:60
#, python-format
msgid "This is not a genuine %s package"
msgstr "これは正式な %s のパッケージではありません"

#: ../apport/ui.py:68
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"古いバージョンのパッケージが利用されています。以下のパッケージをアップグレー"
"ドした上で、それでも問題が発生するかを確認してください:\n"
"\n"
"%s"

#: ../apport/ui.py:152
msgid "unknown program"
msgstr "不明なプログラム"

#: ../apport/ui.py:154 ../apport/ui.py:218 ../apport/ui.py:312
#, python-format
msgid "Problem in %s"
msgstr "%s に問題があります"

#: ../apport/ui.py:155
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"コンピュータに、不具合を自動的に解析して開発者にレポートを送るための十分な空"
"きメモリがありません。"

#. package does not exist
#: ../apport/ui.py:182 ../apport/ui.py:207 ../apport/ui.py:211
#: ../apport/ui.py:243 ../apport/ui.py:251 ../apport/ui.py:304
#: ../apport/ui.py:344 ../apport/ui.py:475 ../apport/ui.py:629
#: ../apport/ui.py:633 ../apport/ui.py:649 ../apport/ui.py:1147
#: ../apport/ui.py:1164 ../apport/ui.py:1631 ../apport/ui.py:1647
#: ../apport/ui.py:1658 ../apport/ui.py:1669
msgid "Invalid problem report"
msgstr "無効な不具合のレポートです"

#: ../apport/ui.py:183 ../apport/ui.py:212
msgid "The report belongs to a package that is not installed."
msgstr "この報告はインストールされていないパッケージによるものです"

#: ../apport/ui.py:208 ../apport/ui.py:634
msgid "This problem report is damaged and cannot be processed."
msgstr "この不具合の報告は破損しており、処理することができません。"

#: ../apport/ui.py:219 ../apport/ui.py:313
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"不具合を報告することができません:\n"
"\n"
"%s"

#: ../apport/ui.py:244
msgid "You are not allowed to access this problem report."
msgstr "この不具合をレポートする為の権限がありません。"

#: ../apport/ui.py:247
msgid "Error"
msgstr "エラー"

#: ../apport/ui.py:248
msgid "There is not enough disk space available to process this report."
msgstr "このレポートを作成するための空きスペースがディスクにありません。"

#: ../apport/ui.py:268
msgid "No package specified"
msgstr "パッケージが特定できません"

#: ../apport/ui.py:269
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"パッケージまたはプロセスIDを特定する必要があります。詳しくは--helpを見てくだ"
"さい。"

#: ../apport/ui.py:278
msgid "Invalid PID"
msgstr ""

#: ../apport/ui.py:279
#, fuzzy
msgid "The specified process ID does not belong to a program."
msgstr ""
"このプロセスを操作する権限がありません。プロセスの所有者か、もしくはrootユー"
"ザとして実行してください。"

#: ../apport/ui.py:287
msgid "Permission denied"
msgstr "許可がありません"

#: ../apport/ui.py:288
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"このプロセスを操作する権限がありません。プロセスの所有者か、もしくはrootユー"
"ザとして実行してください。"

#: ../apport/ui.py:305
#, python-format
msgid "Package %s does not exist"
msgstr "パッケージ %s は存在しません"

#: ../apport/ui.py:476
msgid "Could not determine the package or source package name."
msgstr "パッケージまたはソースパッケージ名を特定できませんでした。"

#: ../apport/ui.py:491
msgid "Unable to start web browser"
msgstr "ウェブブラウザを起動することが出来ません"

#: ../apport/ui.py:492
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "%s を開くためのウェブブラウザを起動することが出来ません"

#: ../apport/ui.py:598
msgid "Network problem"
msgstr "ネットワークの不具合"

#: ../apport/ui.py:600
msgid "Could not upload report data to crash database"
msgstr "クラッシュデータベースにレポートデータをアップロードできません"

#: ../apport/ui.py:624
msgid "Memory exhaustion"
msgstr "メモリ不足"

#: ../apport/ui.py:625
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"あなたのシステムには、このクラッシュレポートを処理するのに十分なメモリがあり"
"ません。"

#: ../apport/ui.py:645
msgid "This problem report does not apply to a packaged program."
msgstr "この不具合の報告はパッケージプログラムに適用できません。"

#: ../apport/ui.py:679
msgid "Problem already known"
msgstr "不具合は既知のものです"

#: ../apport/ui.py:680
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"この不具合は、すでにブラウザ中に表示されたバグレポートで報告されています。開"
"発者にとって役立つような、さらなる情報を追加できるかチェックしてください。"

#~ msgid "&Details..."
#~ msgstr "詳細(&D)..."

#~ msgid "Sorry, %s closed unexpectedly."
#~ msgstr "残念ながら、%s が不意に終了しました。"

#~ msgid "Sorry, the program \"%s\" closed unexpectedly."
#~ msgstr "残念ながら、プログラム \"%s\" が不意に終了しました。"

#~ msgid "&Ignore future crashes of this program version"
#~ msgstr "このプログラムバージョンでは今後クラッシュしても無視する(&I)"

#~ msgid "Restart &Program"
#~ msgstr "プログラムを再起動(&P)"

#~ msgid "Sorry, the package \"%s\" failed to install or upgrade."
#~ msgstr ""
#~ "残念ながら、パッケージ \"%s\" のインストールまたはアップグレードに失敗しま"
#~ "した。"

#~ msgid "Generic error"
#~ msgstr "一般的なエラー"

#~ msgid ""
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "不具合のレポートが送信された後で、フォームに入力してください（入力用ページ"
#~ "をウェブブラウザで自動的に開きます）。"

#~ msgid "&Send"
#~ msgstr "送信(&S)"

#~ msgid "Collecting Problem Information"
#~ msgstr "不具合の情報を集めています"

#~ msgid ""
#~ "The collected information can be sent to the developers to improve the "
#~ "application. This might take a few minutes."
#~ msgstr ""
#~ "収集された情報はアプリケーションを改善するために開発者へ送られます。しばら"
#~ "くお待ちください。"

#~ msgid "Uploading Problem Information"
#~ msgstr "不具合の情報をアップロードしています"

#~ msgid "Unreportable problem"
#~ msgstr "報告不可能な問題"

#~ msgid ""
#~ "The current configuration cannot be supported:\n"
#~ "\n"
#~ "%s"
#~ msgstr ""
#~ "現在の構成をサポートすることができません:\n"
#~ "\n"
#~ "%s"
